--- #YAML:1.0
name:                Tie-ToObject
version:             0.02
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::use::ok:                 0
    Tie::RefHash:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
